#!/bin/bash
# call this script with an email address (valid or not).
# like:
# ./make_cert

echo "make server cert"
openssl req -new -nodes -x509 -out server.csr -keyout server.key -days 3650 -subj "/C=ID/ST=JKT/L=JAKARTA/O=Musobar Media/OU=IT/CN=localhost/emailAddress=musobarmedia@yahoo.com"
echo "make client crt"
openssl req -new -x509 -sha256 -in server.csr -key server.key -out server.crt -days 3650 -subj "/C=ID/ST=JKT/L=JAKARTA/O=Musobar Media/OU=IT/CN=localhost/emailAddress=musobarmedia@yahoo.com"